<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $ocr->filename }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #1a1a1a;
            margin: 0;
            padding: 40px;
        }
        .header {
            border-bottom: 2px solid #c8b89a;
            padding-bottom: 16px;
            margin-bottom: 24px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0 0 6px;
            color: #0c0c0e;
        }
        .meta {
            font-size: 10px;
            color: #666;
        }
        .content {
            white-space: pre-wrap;
            word-break: break-word;
        }
        .footer {
            margin-top: 40px;
            padding-top: 12px;
            border-top: 1px solid #e0e0e0;
            font-size: 10px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $ocr->filename }}</h1>
        <div class="meta">
            Diekstrak {{ $ocr->created_at->format('F j, Y \a\t H:i') }}
            &nbsp;·&nbsp; Mesin: {{ strtoupper($ocr->ocr_engine) }}
            @if($ocr->language)
                &nbsp;·&nbsp; Bahasa: {{ strtoupper($ocr->language) }}
            @endif
            @if($ocr->confidence)
                &nbsp;·&nbsp; Tingkat Akurasi: {{ $ocr->confidence }}%
            @endif
        </div>
    </div>

    <div class="content">{{ $ocr->extracted_text }}</div>

    <div class="footer">
        Generated by {{ config('app.name') }} &mdash; {{ config('app.url') }}
    </div>
</body>
</html>
